config/routes.rb
Rails.application.routes.draw do
	get 'todos', to: 'todos#index'
	get 'todos/new'
	post 'todos', to: 'todos#create'
	get 'todos/:id', to: 'todos#show', as: 'todo'
	get 'todos/:id/edit', to: 'todos#edit'
	patch 'todos/:id', to: 'todos#update'
	delete 'todos/:id', to: 'todos#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def index
		@todos = Todo.all
	end

	def new
		@todo = Todo.new
	end

	def create
		@todo = Todo.new(todo_params)
		@todo.save
		redirect_to todos_path
	end

	def show
		@todo = Todo.find(params[:id])
	end

	def edit
		@todo = Todo.find(params[:id])
	end

	def update
		@todo = Todo.find(params[:id])
		@todo.update(todo_params)
		redirect_to posts_path
	end

	def destroy
		@todo = Todo.find(params[:id])
		@todo.destroy
		redirect_to posts_path
	end

	private
	
	def todo_params
		params.require(:todo).permit(:description, :completed)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">

    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
</html><h1> To Do List </h1>
<% @todos.each do |todo| %>
<div class="well">
  <h1> <% link_to todo.description, todo %> </h1>
  <p> <% todo.completed %> </p>
</div>
<% end %>

 <p> <%= link_to 'Crear ToDo', todos_new_path %> </p>
 <p> <%= link_to 'Crear ToDo', todos_new_path %> </p>

app/views/todos/index.html.erb
</html><h1> To Do List </h1>
<% @todos.each do |todo| %>
<div class="well">
  <h1> <% todo.description %> </h1>
  <p> <% todo.completed %> </p>
</div>
<% end %>

 <p> <%= link_to 'Crear ToDo', todos_new_path %> </p>

app/views/todos/new.html.erb
<%= form_with model: @todo, local: true	do |f| %>
  <%= f.label :description, "To do" %>
  <%= f.text_field :description %>

  <%= f.label :completed, "Check" %>
  <%= f.check_box :completed %>

  <%= f.submit "Enviar" %>
<% end %>

app/views/todos/show.html.erb
<h1> <%= @todo.description %> </h1>
<p> <% @todo.completed %> </p>
<p> <% @todo.created_at %> </p>